ccopy_reg
_reconstructor
p0
(corigae.dataset.images.classification.job
ImageClassificationDatasetJob
p1
c__builtin__
object
p2
Ntp3
Rp4
(dp5
S'username'
p6
Vadmin
p7
sS'_notes'
p8
NsS'tasks'
p9
(lp10
g0
(corigae.dataset.tasks.parse_folder
ParseFolderTask
p11
g2
Ntp12
Rp13
(dp14
S'train_count'
p15
I45002
sS'percent_test'
p16
F0.0
sS'labels_file'
p17
S'labels.txt'
p18
sS'percent_val'
p19
F25.0
sS'val_file'
p20
S'val.txt'
p21
sS'pickver_task_parsefolder'
p22
I1
sS'test_count'
p23
I0
sS'max_per_category'
p24
NsS'pickver_task'
p25
I1
sS'folder'
p26
V/Volumes/d/data/mnist/train
p27
sS'exception'
p28
NsS'current_resources'
p29
NsS'job_id'
p30
S'20171010-234952-5d32'
p31
sS'train_file'
p32
S'train.txt'
p33
sS'traceback'
p34
NsS'label_count'
p35
I10
sS'job_dir'
p36
S'/Volumes/d/github/Origae-6/origae/jobs/20171010-234952-5d32'
p37
sS'parents'
p38
NsS'progress'
p39
F1.0
sS'min_per_category'
p40
I2
sS'val_count'
p41
I14998
sS'status_history'
p42
(lp43
((iorigae.status
Status
p44
S'I'
p46
bF1507650592.533765
tp47
a((iorigae.status
Status
p48
S'R'
p49
bF1507650593.99778
tp50
a((iorigae.status
Status
p51
S'D'
p52
bF1507650595.299017
tp53
asbag0
(corigae.dataset.tasks.create_db
CreateDbTask
p54
g2
Ntp55
Rp56
(dp57
g17
g18
sg34
VException in thread Thread-3:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aException in thread Thread-2:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aException in thread Thread-1:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aException in thread Thread-4:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aException in thread Thread-7:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aException in thread Thread-6:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aException in thread Thread-5:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aException in thread Thread-9:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aException in thread Thread-8:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aException in thread Thread-10:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aTraceback (most recent call last):\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 926, in <module>\u000ahdf5_dset_limit=args['hdf5_dset_limit'],\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 296, in create_db\u000amean_files, **kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 451, in _create_lmdb\u000atime.sleep(0.2)\u000aKeyboardInterrupt
p58
sS'shuffle'
p59
I01
sS'pickver_task_createdb'
p60
I3
sS'encoding'
p61
Vpng
p62
sS'image_dims'
p63
(I28
I28
I3
tp64
sS'resize_mode'
p65
Vsquash
p66
sS'mean_file'
p67
S'mean.binaryproto'
p68
sS'db_name'
p69
S'train_db'
p70
sS'create_db_log_file'
p71
S'create_train_db.log'
p72
sS'entries_count'
p73
Nsg25
I1
sS'distribution'
p74
NsS'image_folder'
p75
NsS'backend'
p76
Vlmdb
p77
sg28
S'error code 1'
p78
sg29
NsS'compression'
p79
S'none'
p80
sS'input_file'
p81
g33
sg30
S'20171010-234952-5d32'
p82
sg36
g37
sg38
(lp83
g13
asS'image_channel_order'
p84
S'BGR'
p85
sg39
I0
sg42
(lp86
((iorigae.status
Status
p87
g46
bF1507650592.533919
tp88
a((iorigae.status
Status
p89
g49
bF1507650595.575176
tp90
a((iorigae.status
Status
p91
S'E'
p92
bF1507650791.901049
tp93
asS'entries_error'
p94
Nsbag0
(g54
g2
Ntp95
Rp96
(dp97
g17
g18
sg34
VException in thread Thread-2:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aException in thread Thread-4:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aException in thread Thread-1:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aException in thread Thread-7:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aException in thread Thread-5:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aException in thread Thread-6:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aException in thread Thread-3:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aException in thread Thread-8:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aException in thread Thread-9:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aException in thread Thread-10:\u000aTraceback (most recent call last):\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner\u000aself.run()\u000aFile "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run\u000aself.__target(*self.__args, **self.__kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 683, in _load_thread\u000adatum = _array_to_datum(image, label, encoding)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 770, in _array_to_datum\u000adatum = caffe_pb2.Datum()\u000aNameError: global name 'caffe_pb2' is not defined\u000aTraceback (most recent call last):\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 926, in <module>\u000ahdf5_dset_limit=args['hdf5_dset_limit'],\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 296, in create_db\u000amean_files, **kwargs)\u000aFile "/Volumes/d/github/Origae-6/origae/tools/create_db.py", line 451, in _create_lmdb\u000atime.sleep(0.2)\u000aKeyboardInterrupt
p98
sg59
I01
sg60
I3
sg61
g62
sg63
g64
sg65
g66
sg67
Nsg69
S'val_db'
p99
sg71
S'create_val_db.log'
p100
sg73
Nsg25
I1
sg74
Nsg75
Nsg76
g77
sg28
S'error code 1'
p101
sg29
Nsg79
g80
sg81
g21
sg30
S'20171010-234952-5d32'
p102
sg36
g37
sg38
(lp103
g13
asg84
g85
sg39
I0
sg42
(lp104
((iorigae.status
Status
p105
g46
bF1507650592.534
tp106
a((iorigae.status
Status
p107
g49
bF1507650595.581269
tp108
a((iorigae.status
Status
p109
g92
bF1507650791.902765
tp110
asg94
Nsbasg17
g18
sg63
g64
sg65
g66
sS'pickver_job'
p111
I2
sS'pickver_job_dataset_image'
p112
I1
sg28
NsS'group'
p113
V
p114
sS'pickver_job_dataset'
p115
I1
sS'persistent'
p116
I01
sS'_name'
p117
VMNIST
p118
sS'form_data'
p119
(dp120
S'form.compression.data'
p121
g80
sS'form.textfile_local_train_images.data'
p122
g114
sS'form.resize_height.data'
p123
I28
sS'form.folder_train.data'
p124
g27
sS'form.folder_val_max_per_class.data'
p125
NsS'form.folder_train_min_per_class.data'
p126
I2
sS'form.textfile_val_folder.data'
p127
g114
sS'form.backend.data'
p128
g77
sS'form.method.data'
p129
Vfolder
p130
sS'form.has_test_folder.data'
p131
I00
sS'form.folder_test_max_per_class.data'
p132
NsS'form.folder_train_max_per_class.data'
p133
NsS'form.folder_val.data'
p134
g114
sS'form.textfile_use_test.data'
p135
I00
sS'form.folder_val_min_per_class.data'
p136
I2
sS'form.has_val_folder.data'
p137
I00
sS'form.textfile_local_labels_file.data'
p138
g114
sS'form.textfile_use_local_files.data'
p139
I00
sS'form.textfile_local_val_images.data'
p140
g114
sS'form.dataset_name.data'
p141
g118
sS'form.resize_width.data'
p142
I28
sS'form.textfile_train_folder.data'
p143
g114
sS'form.group_name.data'
p144
g114
sS'form.folder_test.data'
p145
g114
sS'form.folder_test_min_per_class.data'
p146
I2
sS'form.folder_pct_val.data'
p147
I25
sS'form.resize_mode.data'
p148
g66
sS'form.resize_channels.data'
p149
V3
p150
sS'form.textfile_test_folder.data'
p151
g114
sS'form.folder_pct_test.data'
p152
I0
sS'form.encoding.data'
p153
g62
sS'form.textfile_use_val.data'
p154
I01
sS'form.textfile_shuffle.data'
p155
I1
sS'form.textfile_local_test_images.data'
p156
g114
ssg39
I0
sS'_id'
p157
S'20171010-234952-5d32'
p158
sS'pickver_job_dataset_image_classification'
p159
I2
sg42
(lp160
((iorigae.status
Status
p161
g46
bF1507650592.526571
tp162
a((iorigae.status
Status
p163
g49
bF1507650593.712733
tp164
a((iorigae.status
Status
p165
S'A'
p166
bF1507650791.98459
tp167
asb.